#!/bin/bash
#
# use with:  gdrive push/pull         to copy files
#            gdrive push/pull sync    to synchronize (be careful)
#
#

local=/home/leandro/Drive/
remote=Drive:/

if [ "$1" == "push" ] ; then

  echo "PUSH $local to $remote"

  if [ "$2" == "sync" ] ; then
    #Delete files not present in destination (really synchronizes)
    rclone sync -v --update $local $remote
  fi

  #Does not delete files (safer)
  rclone copy --update $local $remote

fi

if [ "$1" == "pull" ] ; then
  
  echo "PULL $remote to $local"

  if [ "$2" == "sync" ] ; then
    #Delete files not present in destination (really synchronizes)
    rclone sync -v --update $remote $local
  fi

  #Does not delete files (safer)
  rclone copy --update $remote $local

fi



