#!/bin/bash
#
# use with:  gdrive push/pull         to copy files
#            gdrive push/pull sync    to synchronize (be careful)
#            gdrive push/pull check   to check differences
#

local=/home/leandro/Drive/
remote=Drive:/

#
# The script will sync either the current folder or all drive.
# If the current folder is a subfolder of the drive, the current
# folder will be sync. Otherwise, the complete drive will be sync.
#

#
# Default flags
#

flags="-v --update" 

#
# Check if directory is a Drive subfolder
#

current_dir=`pwd`"/"
echo "Current dir: $current_dir"

if [[ "$current_dir" == "$local"* ]] ; then

  echo "Current dir is a drive subfolder"

  len_local=${#local}
  len_current=${#current_dir}
  target=$remote${current_dir:$len_local:$len_current}
  current_local=$current_dir
  current_remote=$target

else

  current_local=$local
  current_remote=$remote

fi

#
# Ignore files listed in .gdriveignore file
#

gdrive_ignore=`pwd`/.gdriveignore
if [ -f $gdrive_ignore ] ; then
  echo "Excluding files on $gdrive_ignore from sync "
  flags="$flags --exclude-from $gdrive_ignore"
fi

# Push or pull

if [[ "$1" == "push" ]] ; then
  type="copy"
  source="$current_local"
  destination="$current_remote"
elif [[ "$1" == "pull" ]] ; then
  type="copy"
  source="$current_remote"
  destination="$current_local"
else
  echo "ERROR: First argument must be 'push', 'pull'"
fi

# Sync, check

if [[ "$2" == "sync" ]] ; then
  type="sync"
elif [[ "$2" == "check" ]] ; then
  type="check"
elif [[ "$2" > " " ]] ; then
  echo "ERROR: Second argument, if any, must be 'sync', 'check'"
fi

echo "RUN: $type \"$source\" to \"$destination\""
run="rclone $type $flags \"$source\" \"$destination\""
echo "Command: $run"
eval $run






